export const PRODUCT_DETAIL_EXAMPLE = {
  id: 1,
  title: 'apratament ne shitje',
  price: 100000,
  city: 'Tirana',
  status: 'active',
  agencyId: 1,
  userId: 4,
  createdAt: '2025-12-17T20:54:10.490Z',
  totalClicks: 0,
  image: [],
  categoryName: 'Komerciale',
  subcategoryName: 'Zyrë',
  listingTypeName: 'Ne-Shitje',
  user: {
    username: 'dawdawaadaswd',
    email: 'asaaaajuhgfaaasaaadad@AllFreeMail.net',
    first_name: 'geri19',
    last_name: 'celmeta',
    phone: null,
    role: 'agent',
    status: 'active',
  },
  agency: {
    agency_name: 'dawdawdawdawd',
    logo: null,
    address: 'tirane',
    phone: null,
    created_at: '2025-12-17T15:30:27.851Z',
    status: 'active',
  },
  isAdvertised: false,
  advertisement: null,
};